### ISSUE TITLE
Lollipop Chart Issues

### ISSUE THREAD

**Issue by rebekahcallkacz** [James-Ashley/sentiment-analysis-dashboard#7]
Lollipop chart generates as it should, but there is an error about "x1" in the inspector that needs to be resolved.

**Comment by James-Ashley** [comment]
This was sorted and is ok to close, correct?

**Comment by rebekahcallkacz** [comment]
Yep - I just closed it. This was an issue with how the the chart was being reloaded vs. when the transition was running.
